### ISSUE TITLE
Implement child immunization view functionality

### ISSUE THREAD

**Issue by maina** [OpenSRP/opensrp-client#383]
- [x] Back button takes you back to home screen
- [x] App name is ZEIR now, instead of ZamJab, so all screens should say ZEIR
- [x] Tapping on Linda Clinic opens the location selector https://github.com/OpenSRP/opensrp-client/issues/399
- [x] Clicking on the horizontal view with the profile image opens profile detail view https://github.com/OpenSRP/opensrp-client/issues/405
- [x] Record all- opens immunization dialog fragment #400
- [x] Tapping an individual vaccine takes you to single vaccine modal https://github.com/OpenSRP/opensrp-client/issues/400
- [x] The background should change depending on child sex: pink for girls, blue for boys
- [x] Record weight- opens records weight dialog https://github.com/OpenSRP/opensrp-client/issues/401
- [ ] Graph icon- opens growth chart screen (May release, no issue yet)
- [x] Siblings- this is based on the child relations whereby each child record in the db table has relationid column whose value is the mother's id. Children with similar relationid are therefore considered as siblings 

**Note when displaying age:**
From age 0 days to 13 days - In days
From age 14 days to 13 weeks, 6 days - In weeks and days
From age 14 weeks to 51 weeks, 6 days - In months and weeks
From age 1 year - In years and months

![immunization](https://cloud.githubusercontent.com/assets/360650/22696428/04877ccc-ed5f-11e6-9285-6f82b04d2c26.png)

![immunization_done](https://cloud.githubusercontent.com/assets/360650/22727223/d5dd2810-ede8-11e6-867b-a4d6aaab04ce.png)

**Comment by maina** [comment]
The background should change depending on child sex: pink for girls, blue for boys

**Comment by cagulas** [comment]
@maina Updated screen below.

![217469972](https://cloud.githubusercontent.com/assets/3488986/23010997/71b776fe-f42f-11e6-8911-c0ed4d369527.png)

**Comment by maina** [comment]
@jasonrogena see above

**Comment by cagulas** [comment]
@jasonrogena think this was already self-explanatory, but just in case you need the variable names from the birth registration form:

![imm-screen-definitions](https://cloud.githubusercontent.com/assets/3488986/23011498/5e680e08-f432-11e6-8dba-e044fa98ad8e.png)

**Comment by rowo** [comment]
@maina @jasonrogena boys card

![boyscolors](https://cloud.githubusercontent.com/assets/1584163/23390862/a18a1f0e-fd3e-11e6-907c-1bb5a056ce1d.png)

**Comment by jasonrogena** [comment]
@rowo How about the vertical separator on the toolbar if it's a girl?

**Comment by rowo** [comment]
Girl Card:
- Top: #e56ce1
- BG: #f9e4f8

Separator is actually two vertical lines, 2px wide each. Left line: #d357cf. Right line: #ef89ec

**Comment by maina** [comment]
[ ] Graph icon- opens growth chart screen (May release, no issue yet) 
#469 will handle this. closing
