### ISSUE TITLE
Fix known issues from ZEIR March 31st release and add missing features

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#446]
Due date: 7th April 2017
Release version should be 1.1.1

- [x] Mother/guardian DOB should be blank when filling the birth registration form. Only default to 01/01/1960 if form is submitted with this field not filled in. If this field is not filled in, it should also show as blank in the detailed view, and if birth registration form is then edited, this field should still show as blank in the edit form view. If the user adds a DOB for the mother/guardian in the edit form view, this should then replace or update the 01/01/1960 DOB in the backend and in OpenMRS.
- [x] The "Search out of catchment records" button from the no matching person dialog should take the user to the advanced search page and prefill the ZEIR ID field with the ID read from the QR code scan.
- [x] On the advanced search page, don't show the labels for each field twice.
- [x] Fix all issues on the advanced search page and search results page.
- [x] The avatar for girls on the weight modal should be pink.
- [x] Make sure all the fields from the birth registration form appear in the "Registration Data" view in the detailed view. Then make sure all fields are pre-populated into the birth registration form edit view. @raihan-mpower 
- [x] Fix the issue where, on some child records, Linda clinic appears with the entire location tree in the detailed view (see child "Mark Chipango" with ZEIR ID 1000009"). @raihan-mpower 
- [x] Add QR code override to the ZEIR ID field in the birth registration form.
- [x] The immunisation page in the detailed view does not match that immunisations in the vaccine card view. For instance, when registering a kid, all the vaccines show as red (overdue status) in the detailed view. When a vaccine is given in the vaccine card view, it does not update in the detailed view, etc. @raihan-mpower 
- [x] Remove child DOB field in the reported deceased form.
- [x] Add adverse event form https://github.com/OpenSRP/opensrp-client/issues/425
- [x] In order to see the update to the child's status (active, inactive, lost to followup) you have to go back one screen then open the detailed view screen again. This should be automatic. @raihan-mpower 
- [x] Fix the icons for the statuses, i.e, only active should be green, while inactive and lost to followup should be grey. Lost to followup needs to be resized, @maina to ask @rowo for the icons that are needed.
- [x] @cagulas to talk to @rowo about the statuses and how to show them in the edit menu
- [x] The inactive and lost to followup statuses should appear in the register view (home screen) as well.
- [x] "Record weight" button on the home screen is not centered
- [ ] Add BCG scar reminder and record BCG 2 functionality https://github.com/OpenSRP/opensrp-client/issues/426
- [x] Implement weight reminder (issue to be created I think)
- [ ] Mother lookup (might not get finished this week) https://github.com/OpenSRP/opensrp-client/issues/421
- [x] Make weight button white and un-editable after weight recorded for a period of 24 hours, then revert to grey "Record weight" button
- [ ] Edit weight option on the detailed view screen should give user the option to edit each 
previous weight. Right now, the app seems to randomly pick a previous weight to launch in the edit modal.
- [x] Add confirm form close if you try to exit out of the Birth Registration form to remind the user that they'll lose all the data they have entered so far.
- [x] Set up empty OpenMRS instance
- [x] Carolyn to enter metadata into OMRS when the above is finished
- [ ] @geoffreymuchai to test data import this week
- [x] Zones are not in order in the Residential Area field in the birth registration form
- [x] Check to see if new date widget can be centered in the modal
- [x] Correct the constraint logic on Mother/guardian DOB field. Today (April 3, 2017), I was able to enter a birthdate of April 6, 2007 (think it should be capped at April 2, 2017).
- [ ] Make sure all the required message alerts in the Birth Registration form are aligned (see screenshot below)
- [x] All required fields have a space between the last letter of the last word and the asterisk (*) except the first field "Child's home health facility". Need to add a space here as well.
- [x] @cagulas to talk to @rowo about how to show app is currently syncing
- [ ] After a kid is registered, you should be able to immediately see the next due vaccines and be able to record the next due vaccines. Currently, you need to sync with the scheduling server first to do both.
- [ ] Scheduling sync doesn't seem to be triggered when the user does a manual sync. For child Pan Cakes, I synced the tablet, but the scheduling reminder did not update (it should have gone from Due at birth (white) to Due at birth (blue).

![screenshot_20170403-163908](https://cloud.githubusercontent.com/assets/3488986/24612527/30d666e4-188e-11e7-8488-ad45453aa493.png)

**Comment by raihan-mpower** [comment]
I can try looking into the following issues

- Make sure all the fields from the birth registration form appear in the "Registration Data" view in the detailed view. Then make sure all fields are pre-populated into the birth registration form edit view.

- Fix the issue where, on some child records, Linda clinic appears with the entire location tree in the detailed view (see child "Mark Chipango" with ZEIR ID 1000009").

-  The immunisation page in the detailed view does not match that immunisations in the vaccine card view. For instance, when registering a kid, all the vaccines show as red (overdue status) in the detailed view. When a vaccine is given in the vaccine card view, it does not update in the detailed view, etc.

- in order to see the update to the child's status (active, inactive, lost to followup) you have to go back one screen then open the detailed view screen again. This should be automatic.

**Comment by cagulas** [comment]
Thanks, @raihan-mpower, I've added your name next to these in the original issue, so no one else picks them up.

**Comment by cagulas** [comment]
Report Adverse Event form is signed off, so it can be worked on now. I have noted it's no longer blocked in the issue.

**Comment by cagulas** [comment]
Quick update on the UI issues - I talked to @rowo about the issues with the status change and a couple of other things, like syncing, etc. He'll update this issue with proposed UI changes.

**Comment by rowo** [comment]
A few edits so far:
1. On home screen, add check mark to vaccines recently recorded ala weight recently recorded - https://projects.invisionapp.com/d/main#/console/10214563/227834047/preview
2. Change how status is changed by moving choices to a simple menu: https://projects.invisionapp.com/d/main#/console/10214563/227917705/comments

**Comment by raihan-mpower** [comment]
"Make sure all the fields from the birth registration form appear in the "Registration Data" view in the detailed view. Then make sure all fields are pre-populated into the birth registration form edit view. "
i am able to get all fields except residential address and other residential area
@jasonrogena can you look into it?

**Comment by raihan-mpower** [comment]
anyone on to this 

- [ ] "Edit weight option on the detailed view screen should give user the option to edit each
previous weight. Right now, the app seems to randomly pick a previous weight to launch in the edit modal."

i can pick it up if not.....

**Comment by rowo** [comment]
## Sync
### Question
- @jasonrogena @raihan-mpower what time does the Last Sync reflect — when the sync button is pressed or when the syncing process is finished? It should be when it's done I think, if it isn't already.

### Edits
- [ ] After sync is clicked, we need some sort of indication that (1) the sync button was clicked and (2) it is currently syncing. A snackbar at the bottom would be nice. So after you click "Sync" in the menu:
  - The menu closes (like it does now) and a snackbar shows up:
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812096/c55bd3ca-1b96-11e7-9be8-49a25cb512b4.png" width="300">
    Additionally, we could replace the initials avatar with an animated sync icon:
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812448/20020884-1b98-11e7-8a1a-4b53ac2555c9.png" width="200">
  - When the sync is complete, this shows up: 
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812120/dd5db696-1b96-11e7-9414-2e38186a8bdc.png" width="300"> 
  - If there's an error, this shows up (and disappears if click happens anywhere else):
    <img src="https://cloud.githubusercontent.com/assets/1584163/24812238/410eee76-1b97-11e7-8be1-07074a84dc90.png" width="300">
-  [ ] If the user opens the menu up while syncing is happening, what appears is the label should change to "Syncing...". It would be nice if the sync icon was animated and rotated. Not a big deal though if not.

### Tips on snackbar interaction from [Material guidelines](https://material.io/guidelines/components/snackbars-toasts.html#):
- Snackbars appear above most elements on screen, and they are equal in elevation to the floating action button. However, they are lower in elevation than dialogs, bottom sheets, and navigation drawers.
- Upon entrance, snackbars animate upwards from the bottom edge of the screen. When they appear, they do not block input.
- They exit by being swiped off-screen or automatically disappear after a timeout or user interaction elsewhere (such as summoning a new surface or activity).

**Comment by cagulas** [comment]
I moved all remaining work into new issues https://github.com/OpenSRP/opensrp-client/issues/475 and https://github.com/OpenSRP/opensrp-client/issues/474. Closing this.
