### ISSUE TITLE
Fix issues in ZEIR April 7th release and add new UI elements

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#475]
These are listed in order of priority to work on:

**Schedules**
- [x] Immediately after a new kid is registered, the first vaccines should show up immediately. For the child Smith, 3d, ID: 1021021, I had to sync the tablet for the birth vaccine schedule to appear. This should NOT require a sync and it should NOT require an internet connection.
- [x] For a new child that is registered, it is showing Measles 1 and 2 are expired for some reason; it shouldn't show this (see child Smith, 3d, ID: 1021021)
- [x] When you record a vaccine, then undo the vaccine, then record it again with a different date, it shows the vaccine was given on the original date (that had been undone). For example, for child Robin Hood, I gave BCG on 11/4/17, then undid the vaccine, then gave it again, but on a different date, 16/1/17, but it still shows as 11/4/17. CG: update, it seems you cannot record a previous weight even the first time around. It always shows that today's date was selected.

**Mother lookup**
- [x] Implement mother lookup functionality in the form https://github.com/OpenSRP/opensrp-client/issues/421

**Edit birth registration form**
- [x] The date widget seems broken on Huawei devices
- [x] When editing the birth registration form, the QR code scan should be activated, as this is how the child can be assigned a new ZEIR ID if their card or ID is ever lost. This is also required for the initial project phase, where kids will be getting a QR code sticker, which will need to override the current ID.
- [x] The user still has to select the home health facility again when editing the birth registration form data. This should be pre-populated, but they can edit it if needed.
- [x] Mother/guardian DOB field should be editable (see data dictionary)
- [x] Mother/guardian NRC number should be editable (see data dictionary)
- [x] Birth health facility should NOT be editable (see data dictionary)
- [x] Child's residential area is not populated in the form when it should be. This field should then be editable.
- [x] Other residential area is not populated in the form when it should be. This field should then be editable.
- [x] HIV exposure is not populated in the form when it should be. It should then be NOT editable.

**Location hierarchies**
- [x] The `Residential_Area` question in the birth registration form needs to go one level down and show the residential area (the level below the zone). This is what the user needs to select for this field, not the zone.

**Detailed view**
Assigning this entire section to @raihan-mpower to start working on.
- [x] HIV exposure (i.e., PMTCT status) is still not showing up in the detailed view (Registration Data tab "HIV exposure" and Under Five History tab "PMTCT status"), and it seems to have disappeared from the weight modals as well
- [x] Child's residential area (and other residential area) are still not showing up in the detailed view (Raihan requested help from @jasonrogena on this one)
- [x] After you submit edits in the birth registration form, the edits do not appear in the detailed view immediately, you have to re-visit the page to see the edited fields reflect
- [x] If you mark a child as inactive, it appears right away in the detailed view, but if you mark as active again, you still have to re-visit the page to see the update. This should be automatic.
- [x] Buttons should all be rounded on the Under Five History tab (see below)
![round](https://cloud.githubusercontent.com/assets/3488986/24860242/5dbc027c-1dfc-11e7-9cc2-a47a3a4f1c14.png)
- [x] The weights should be ordered according to age in the detailed view. See child Julius Muchai (ID: 1003508). I took the weight today (4 days old), but it's appearing second in the last 5 weights, when it should appear at the top. Order according to age.
- [x] The edit icon is shown on the profile picture in the vaccine card, when this isn't editable by tapping. At the same time, the profile picture on the detailed view, which can be edited by tapping, does not show the icon. I would remove the edit icon on the profile picture in the vaccine card and add it instead to the profile picture on the detailed view screen.
- [x] The vaccine dates on the Under Five History tab are not matching the dates in the vaccine card tab, and they are appearing in a weird format. See child Julius Muchai (ID: 1003508), he received OPV 0 and BCG on April 10, 2017, but on the detailed view, it shows these dates as 07-10-0012. I don't know what this means for the year to be shown as 0012, but it should match the dates on the vaccine card. Same goes for the child Beth Drew.

**Other issues**
- [x] From https://github.com/OpenSRP/opensrp-client/issues/470: Format on date picker in registration form (and elsewhere) needs to change to dd-mmm-yyyy. Think it's still good to show the month in letters not numbers, so let's try to keep that.
- [x] Profile pics  randomly appear for multiple child records https://github.com/OpenSRP/opensrp-client/issues/442

**Comment by cagulas** [comment]
@maina @jasonrogena @keymane @raihan-mpower We are trying to aim for another release by the end of this week. I have put in bold the issues that we should tackle first this week to get into the release based on observation and feedback from the Zambia field visits last week.

**Comment by mberg** [comment]
@cagulas i thought the lowest structured area we were doing was zone.  Does this mean we need to support org hiearchy for things below zones?  I thought this is something they were just going to type in.

**Comment by cagulas** [comment]
@mberg Below zone, there is Residential Area. PATH team provided the mapping for all zones and residential areas. The health worker types in the residential address and landmark. Zones and residential areas were already entered into DHIS2.

**Comment by cagulas** [comment]
QA results:
- [ ] If you change the child's ZEIR ID by scanning a new QR code in the birth registration form, it reverts to the old ID again after pressing the sync button
- [ ] A change to the mother's NRC number does not immediately reflect in the detailed view. One must go back to the home screen, then revisit the detailed view to see the update.
- [ ] The record weight button should not be shown on the home screen if a child is marked as inactive or lost to followup.
- [ ] HIV exposure (i.e., PMTCT status) is now showing up in the detailed view (Registration Data tab) but it's still not showing up on the Under Five History tab "PMTCT status", and it is still missing from the weight modals, i.e., when recording weight, it should show CE, MSU, CNE underneath the ZEIR ID and age.
- [ ] I am unable to register a new child as the device notified me that there were no IDs on the device. I was connected to the internet and tried to sync, but it seemed no new IDs were being synced. If this is the case for all users, this is an URGENT issue to fix.
- [ ] I was unable to test date widget fix on Huawei, so Jason will need to test on the Huawei device.
- [ ] Some children in the biddemo user are showing a tick mark on the home screen, indicating vaccines were given, but upon visiting the vaccine card page, the vaccines are not recorded as indicated on the home screen.
- [ ] The Zones in the service location dropdown are no longer showing for Linda when logged in as the biddemo user.
- [ ] Child's residential area is STILL not populated in the edit birth registration form when it should be. This field should then be editable.

**Since I was unable to open the birth registration form, I was not able to QA the following fixes, so someone will need to do this:**

- Immediately after a new kid is registered, the first vaccines should show up immediately. For the child Smith, 3d, ID: 1021021, I had to sync the tablet for the birth vaccine schedule to appear. This should NOT require a sync and it should NOT require an internet connection.
- For a new child that is registered, it is showing Measles 1 and 2 are expired for some reason; it shouldn't show this (see child Smith, 3d, ID: 1021021)
- Implement mother lookup (first name, last name, DOB) functionality in the form #421
- Other residential area is not populated in the form when it should be. This field should then be editable.
- “Other” field for birth health facility being added.
- Mother/guardian DOB is showing as "31-12-1959" in the detailed view when the field was left blank in the form. This should remain blank in the detailed view. It should only show a DOB if the user then edits the birth registration form and adds a DOB for the mother. Currently, if you open the birth registration form to edit, it shows the default DOB in the registration form, and the user cannot even edit it.
- The mother's default DOB should be 01-01-1960, not 31-12-1959.

**Comment by cagulas** [comment]
Closing this issue. All remaining items have been transferred to new issues.
