### ISSUE TITLE
Implement current stock screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#479]
- [x] Going back one screen returns you to the stock control card view (https://github.com/OpenSRP/opensrp-client/issues/478)
- [x] Tapping the user's initials or swiping from the left opens the side menu
- [x] The vaccine stock shown (in the screen below, M/MR) is based on which vaccine you select from the stock control card view (https://github.com/OpenSRP/opensrp-client/issues/478) (e.g., if you tap on OPV from the stock control card view, you see the screen below, but for OPV, and so on, NB: mockups only created for M/MR)
- [x] Tapping on "Stock Planning" or swiping to the right, switches the screen to the Stock Planning screen https://github.com/OpenSRP/opensrp-client/issues/483
- [x] M/MR Stock: 14 vials is auto-calculated from the forms that the user fills out (e.g., received, issued, loss/adj); this value should match the value shown on the stock control card view
- [x] "Received" button opens the stock received form for that vaccine https://github.com/OpenSRP/opensrp-client/issues/480
- [x] "Issued" button opens the stock issued form for that vaccine https://github.com/OpenSRP/opensrp-client/issues/481
- [x] "Loss/Adj" button opens the stock loss/adjustment form for that vaccine https://github.com/OpenSRP/opensrp-client/issues/482
- [x] A row in the table is created for every Received, Issued, and Loss/Adj form submission. The values shown in the table come from those form submissions. The table should be paginated like the register view
- [x] The rows should be sorted by date, with most recent date on top
- [x] Date should be DD/MM/YY format

![225059911](https://cloud.githubusercontent.com/assets/3488986/25885124/5f39f81e-355f-11e7-9127-10a6d2df7d80.png)

**Comment by raihan-mpower** [comment]
@rowo @maina  need icons to be used for this screen

**Comment by rowo** [comment]
@raihan-mpower emailing you some SVGs or would you prefer PNGs?

**Comment by raihan-mpower** [comment]
@rowo it is ok , i have converted them to pngs myself

**Comment by cagulas** [comment]
@raihan-mpower Here are my suggestions:

- [ ] Breadcrumb at the top is missing the vaccine name; it should be: Stock Control > BCG, etc.
- [ ] There are too many spaces between BCG Stock and 0 vials. Only put one space after the colon.
- [ ] Can we reduce the empty space between the icons for the forms and the text, eg. the plus (+) button is very far from the "Received" text on my Samsung device. Same goes for the issued and loss/adj form button icons.
- [ ] Add space between Issued and (-) in column header
- [ ] When selecting "Physical recount" option in the Loss/Adj form, it displays in the table as "Physical_recount" with the underscore. It should not show the underscore.

**Comment by cagulas** [comment]
Lgtm.
