### ISSUE TITLE
Implement stock received native form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#480]
- [x] Tapping the back button or the cancel button should open the form close confirmation message. If confirmed, the user should go back to the current stock screen for that vaccine https://github.com/OpenSRP/opensrp-client/issues/479
- [x] The fields in the form should follow the fields defined in the [data dictionary spreadsheet](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1075761441), see the "Stock Control" tab
- [x] Form styling uses same library as birth registration form
- [x] Tapping "Confirm" submits the form and updates the table in the current stock screen for that vaccine https://github.com/OpenSRP/opensrp-client/issues/479
- [x] Can do error states if the user tries to click "Confirm" and required fields aren't all completed. If we are using the same library as birth registration, we can treat confirm button on this form the same way.
- [x] All of the above actions should be supported both online and offline
- [x] Clicking on other radio button displays a text field to enter vaccine source. This field has required constraint. See #481
 
![stock-received](https://cloud.githubusercontent.com/assets/3488986/24952084/269c728e-1f7f-11e7-824f-7adb4dd24ea7.png)

**Comment by cagulas** [comment]
@raihan-mpower Here are my suggestions:

- [ ] DHO and Other options are WAY too big!
- [ ] The upper constraint is missing on the date stock received field. It shouldn't allow dates more than 1 calendar month ago. This applies to all stock received forms.
- [ ] The asterisk is missing on vials received. This should be a required field.
- [ ] Remove the space before the colon on the New balance field.

**Comment by cagulas** [comment]
Lgtm.
