### ISSUE TITLE
Implement stock planning screen

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#483]
- [x] Going back one screen returns you to the stock control card view (#478)
- [x] Tapping the user's initials or swiping from the left opens the side menu
- [x] The vaccine stock planning shown below (in the screen below, M/MR) is based on which vaccine you select from the stock control card view (#478) (e.g., if you tap on OPV from the stock control card view, you see the screen below, but for OPV, and so on, NB: mockups only created for M/MR)
- [x] Tapping on "Current Stock" or swiping to the left, switches the screen to the Current Stock screen https://github.com/OpenSRP/opensrp-client/issues/479
- [x] 3 month M/MR stock used shows the number of whole vials of the vaccine stock used for the most recent 3 months. E.g., if the current month is April, then the graph and the section below show the vials used for the months of March, February, and January, in that order (ie. most recent month on top).
- [x] The three month average takes the average (rounded to the higher whole number, i.e., 7.2 rounds to 8) of the number of vials used for the most recent three months
- [x] Current M/MR stock: 14 vials is auto-calculated from the forms that the user fills out (e.g., received, issued, loss/adj); this value should match the value shown on the stock control card view and the current stock view.
- [x] Number of active children shows the total number of children currently registered in the app for this clinic with an active status (i.e, do not count inactive or lost to followup or deceased children), disaggregated by two age groups (0-11 months and 12+ months) and shown for the current month and the most recent month. The difference is this month minus last month. This is based on the first of the month. So calculate the total number of kids currently in the app on the first of the month.
- [x] Due M/MR next month shows the total number of vials needed for next month based on the number of children in the app for this clinic with active status (do not count inactive, lost to followup, or deceased) that will be due for M/MR in the next month based on the vaccine schedule. E.g., if this month is April, it shows the number of vials needed for the kids that will be due for M/MR vaccine anytime in the month of May. Note: "Calculated from current active children that will be due for M/MR next month."
- [x] Average M/MR waste rate - this calculates the percentage average waste rate of the vaccine. This is determined by the number of vaccinated children divided by the total number of possible doses that could have been given. For e.g., say this week 78 children were vaccinated with OPV, and 5 vials were marked as used or wasted. The calculation would be 1 - (78 / (5*20)) = 0.22 or 22% wastage.

![223794304](https://cloud.githubusercontent.com/assets/3488986/25885181/abc0c94c-355f-11e7-910e-61153a5c0c46.png)

**Comment by cagulas** [comment]
@raihan-mpower Here are my suggestions:

- [ ] The vaccine name is missing in the breadcrumb at the top - it should be: Stock Control > M/MR
- [ ] Can we match the blue shown in the graph (x-axis and graph line) to the blue font of the number of vials text?
- [ ] The numbers on the y-axis should be whole numbers only. Right now, I'm seeing decimals like 22.5 vials, etc.
- [ ] Need to add left padding again (see mockup)
- [ ] How is the x-axis plotted? For instance, I add stock received for June, and the line is plotted in what looks to be May 2017? I think the vertical line on the graph represents the start of the month, i.e. all stock for that month appears to the right of the line that is labeled for the month on the x-axis.
- [ ] Remove the extra spaces before the number of vials in the "Current [vaccine] stock" label.
- [ ] Don't capitalize "Children" in "Number of active children"
- [ ] Add space before and after the dash in number of active children section, i.e. "0 - 11 months" and "12 - 59 months".
- [ ] Don't capitalize "Months"
- [ ] The difference column is missing the +/- symbol to indicate if the difference is positive or negative.
- [ ] Don't capitalize "Next" in "Due [vaccine] Next month"
- [ ] Remove space before colon in "Due [vaccine] next month"
- [ ] Add period to the end of the sentence under due next month.
- [ ] I think the waste rate can be rounded to a whole number percentage.

**Comment by cagulas** [comment]
Since some of these are difficult to QA on the tablet, @maina will do a code review of the following:

- [ ] 3 month M/MR stock used shows the number of whole vials of the vaccine stock used for the most recent 3 months. E.g., if the current month is April, then the graph and the section below show the vials used for the months of March, February, and January, in that order (ie. most recent month on top).
- [ ] The three month average takes the average (rounded to the higher whole number, i.e., 7.2 rounds to 8) of the number of vials used for the most recent three months.
- [ ] Number of active children shows the total number of children currently registered in the app for this clinic with an active status (i.e, do not count inactive or lost to followup or deceased children), disaggregated by two age groups (0-11 months and 12+ months) and shown for the current month and the most recent month. The difference is this month minus last month. This is based on the first of the month. So calculate the total number of kids currently in the app on the first of the month.
- [ ] Due M/MR next month shows the total number of vials needed for next month based on the number of children in the app for this clinic with active status (do not count inactive, lost to followup, or deceased) that will be due for M/MR in the next month based on the vaccine schedule. E.g., if this month is April, it shows the number of vials needed for the kids that will be due for M/MR vaccine anytime in the month of May. Note: "Calculated from current active children that will be due for M/MR next month."
- [ ] Average M/MR waste rate - this calculates the percentage average waste rate of the vaccine. This is determined by the number of vaccinated children divided by the total number of possible doses that could have been given. For e.g., say this week 78 children were vaccinated with OPV, and 5 vials were marked as used or wasted. The calculation would be 1 - (78 / (5*20)) = 0.22 or 22% wastage.

**Comment by cagulas** [comment]
@raihan-mpower Noticed a few things:

- [ ] I think the vertical line on the graph represents the start of the month, i.e. all stock for that month appears to the right of the line that is labeled for the month on the x-axis. CG update: For this one I don't see any change. I added stock (25 vials) on the date of May 28, and the line that shows this on the graph is plotted before the May 2017 x-axis mark. I think the line on the graph designates the start of the month, not the end of the month.
- [ ]  The numbers on the y-axis should be whole numbers only. Right now, I'm seeing decimals like 22.5 vials, etc. CG update: Is this something that will take more time to fix?
- [ ] I noticed that the app orientation isn't locked to portrait in the stock module, and you can rotate to landscape mode. This should be locked to portrait like the rest of the app I think.

**Comment by cagulas** [comment]
Moving all remaining issues here: https://github.com/OpenSRP/opensrp-client-path/issues/23
