### ISSUE TITLE
Add daily tallies view in the HIA2 reporting module

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#517]
- [x] The daily tallies view (see below) is the first tab that the user lands on when selecting the HIA2 reporting module in the app.
- [x] The RW icon shows the initials of the user who is currently logged in.
- [x] Tapping the user initials icon or swiping from the left side opens the app side menu, where the user can navigate to other modules in the app.
- [x] Sections are created for each calendar month, i.e., March 2017, April 2017, and so on.
- [x] Calendar months should appear in reverse chronological order, with most recent month on top.
- [x] Underneath each month section, the daily tally summaries appear for the days they are created. Tapping on a specific daily summary opens the daily tally summary for that day (https://github.com/OpenSRP/opensrp-client/issues/518).
- [x] The daily tally summaries shown under each calendar month should be ordered chronologically.
- [x] Tapping on the "Draft Reports" tab opens the Draft Reports view (https://github.com/OpenSRP/opensrp-client/issues/519) (please note, the label for the tab should actually be "Draft Monthly", which can be seen in the issue).
- [x] Tapping on the "Sent Reports" tab opens the Sent Reports view (https://github.com/OpenSRP/opensrp-client/issues/521) (please note, the label for the tab should actually be "Sent Monthly", which can be seen in the issue).

![234670714](https://cloud.githubusercontent.com/assets/3488986/26538888/0f160fe2-4452-11e7-88b2-b7aa80f6dabc.png)

**Comment by rowo** [comment]
![icon-report](https://user-images.githubusercontent.com/1584163/26878339-25340b5c-4b5b-11e7-9755-7955808a13af.png)

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
Am reopening the issue. I'm noticing a few things:

- [ ] A few daily tallies are showing in the future. I'm seeing a 08 June 2100 daily tally, a 05 May 2026 daily tally, etc. Not sure how these are possible, since most fields have date constraints that don't allow you to select a date in future.
- [ ] I recorded a few services (OPV 0 and BCG) for June 28 for a newly registered child, yet the values for these vaccines in the HIA2 daily tally are showing as 0, so not sure if the values are getting updates.

**Comment by cagulas** [comment]
Closing this. The automated tests should fix any calculation issues.

https://github.com/OpenSRP/opensrp-client/issues/543
