### ISSUE TITLE
Add the draft monthly tab view in the HIA2 reporting module

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#519]
- [x] The draft monthly view (see below) is the tab that the user lands on when selecting the Draft Monthly tab when the user is in the HIA2 reporting module.
- [x] The RW icon shows the initials of the user who is currently logged in.
- [x] Tapping the user initials icon or swiping from the left side opens the app side menu, where the user can navigate to other modules in the app.
- [x] Tapping the Daily Tallies tab opens the Daily Tallies summary view (https://github.com/OpenSRP/opensrp-client/issues/517).
- [x] Tapping the Sent Monthly tab opens the Sent Monthly view (https://github.com/OpenSRP/opensrp-client/issues/521).
- [x] The number shown in parentheses in the tab name is the number of draft (i.e. unsent) HIA2 monthly reports.
- [x] When there are no draft reports saved, the screen below is shown. The "Illustration" icon is a placeholder until @rowo sends the appropriate icon.
- [x] The "Start new report" button opens the HIA2 monthly report form, when one is available to fill out. It is greyed out and not tappable when there is no monthly report available to fill out (Screen 1).
- [x] Add the snackbar notification when no reports are available to fill out (Screen 2).
- [x] Add logic for enabling the start new report button (Screen 3). The button should only be enabled when a new report is available to be filled out. A new monthly report is available on the 1st of the month. E.g. March 2017 report becomes available on April 1st, April 2017 report becomes available on May 1st, and so on.
- [x] When selecting the start new report button, a menu of available reports is shown (Screen 4). Tapping on an option in the menu opens the HIA2 monthly report form for that calendar month (https://github.com/OpenSRP/opensrp-client/issues/520).
- [x] When a draft report is saved, the report month name and the date the report was initially started and saved is shown (Screen 5). Tapping the saved report returns the user to the HIA2 monthly report form to begin where they left off (https://github.com/OpenSRP/opensrp-client/issues/520).

Screen 1: No draft reports, no reports available to start.
![235342220](https://cloud.githubusercontent.com/assets/3488986/26539537/a236c002-4455-11e7-9456-63586aa59010.png)

Screen 2: User taps Start new report button when no reports are ready to be filled in.
![235342234](https://cloud.githubusercontent.com/assets/3488986/26539743/c08c0f5c-4456-11e7-8081-1ba03fe464c7.png)

Screen 3: Button is enabled when a report is ready to be filled out.
![234670700](https://cloud.githubusercontent.com/assets/3488986/26539792/ef2962b0-4456-11e7-9e45-1d13651f2d4f.png)

Screen 4: Available reports menu
![234670705](https://cloud.githubusercontent.com/assets/3488986/26539870/3dd55cde-4457-11e7-90ff-d918f48935ac.png)

Screen 5: Draft report saved
![234670711](https://cloud.githubusercontent.com/assets/3488986/26540783/a3aaf966-445b-11e7-93fe-912ef331424c.png)

**Comment by cagulas** [comment]
Comments from QA below:

- [ ] The number shown in parentheses in the tab name is the number of draft (i.e. unsent) HIA2 monthly reports. CG update: for this one, I think the intention was to put the total number of reports that they started but didn't submit yet. Right now, I think it's showing the total number of available reports to start filling out, but it should be showing the total number of draft reports saved.
- [ ] I don't know if the date constraint on the available draft reports is in place. For instance, a draft report should only be available to select after the calendar month is over. So, e.g. June 2017 shouldn't yet be available to fill out until July 1st and so on.
- [ ] When a draft report is saved, the report month name and the date the report was initially started and saved is shown (Screen 5). Tapping the saved report returns the user to the HIA2 monthly report form to begin where they left off (#520). CG update: not finished yet.

**Comment by cagulas** [comment]
Lgtm.
