### ISSUE TITLE
Add the HIA2 monthly report form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#520]
- [x] This native Android form opens when you select an individual calendar month from the menu of available monthly forms to fill out in the Draft Monthly tab (Screen 1) (https://github.com/OpenSRP/opensrp-client/issues/519).
- [x] When selecting the back arrow or pressing the back button on the tablet, the user will get a dialog (not pictured) to ask whether they want to save changes or not. If yes, the changes to the form are saved and the user is taken back to the Draft Monthly tab view (https://github.com/OpenSRP/opensrp-client/issues/519). If the user does not want to save changes, changes are not saved and the user is taken back to the Draft Monthly tab view.
- [ ] Selecting the SAVE button saves the changes in the form and shows a snackbar message that the changes have been saved (Screen 2). The user remains on this page after saving.
- [x] The section headers are the same as those in the daily tally summary view (https://github.com/OpenSRP/opensrp-client/issues/518):
- Under 5 Clinic Attendance
- Growth Monitoring and Nutrition
- Immunisation
- Vitamin A, Deworming, and ITNs
- [x] The indicator labels should follow the exact text and order as seen in the reporting data dictionary spreadsheet [here](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=2010018538). See the "Label" column in the spreadsheet.
- [ ] Not pictured, but the ID of the indicator should be shown in the form as well. See the "Name" column in the reporting data dictionary. The ID can come before the indicator name, followed by a colon, e.g.: "CHN1-005: Attendance child health <12months (male)"
- [ ] The values entered are pre-populated from the app, but editable here. Summed indicators, e.g. attendance total, are not editable as they sum numbers in the form. 
- [x] The end of the form has a blue confirm button (Screen 3). 
- [x] When selecting the blue confirm button, a submission confirmation dialog appears (Screen 4). The Date displayed is today's date. The User displayed is the name of the logged in user. Selecting the Cancel button or tapping outside the dialog takes you back to the draft form. Selecting the Send button submits the report to DHIS2 and takes the user to the Sent Monthly tab in the HIA2 reporting module (https://github.com/OpenSRP/opensrp-client/issues/521).

Screen 1: View when the user opens the form to fill in.
![234670706](https://cloud.githubusercontent.com/assets/3488986/26540246/15580d9a-4459-11e7-8eaf-6d830782d9f8.png)

Screen 2: User selects the Save button.
![234670707](https://cloud.githubusercontent.com/assets/3488986/26540267/3558ecf4-4459-11e7-864c-14f38247dc7a.png)

Screen 3: End of the form showing the confirm/submit button.
![234670709](https://cloud.githubusercontent.com/assets/3488986/26540347/a83f5014-4459-11e7-9b31-2f4fe1e2d56a.png)

Screen 4: Confirm and submit dialog.
![234670710](https://cloud.githubusercontent.com/assets/3488986/26540363/ce3931c2-4459-11e7-93ee-58e78e81b06b.png)

**Comment by cagulas** [comment]
All remaining issues moved to new issue: https://github.com/OpenSRP/opensrp-client-path/issues/21. Closing this.
