### ISSUE TITLE
Add the sent monthly tab to the HIA2 reporting module

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client#521]
- [x] The sent monthly view (Screen 1) is the tab that the user lands on when selecting the Sent Monthly tab when the user is in the HIA2 reporting module. Please note, the label in Screen 1 says Sent Reports, this was changed, so please make sure it says "Sent Monthly" when adding this view.
- [x] The RW icon shows the initials of the user who is currently logged in.
- [x] Tapping the user initials icon or swiping from the left side opens the app side menu, where the user can navigate to other modules in the app.
- [x] Tapping on the "Draft Monthly" tab opens the Draft Monthly view (#519).
- [x] Tapping the Daily Tallies tab opens the Daily Tallies summary view (#517).
- [x] Sections are created for each calendar year, i.e., 2016, 2017, and so on.
- [x] Calendar years should appear in reverse chronological order, with most recent year on top.
- [x] Underneath each year section, the sent HIA2 monthly reports appear for the months they were sent. The date shown below the report month name is the date the report was confirmed and sent. And the user that submitted the report is shown as well.
- [x] The HIA2 month reports shown under each calendar year should be ordered reverse-
 chronologically.
- [x] Tapping on a specific month opens the HIA2 report month summary view (https://github.com/OpenSRP/opensrp-client/issues/522).

Screen 1: Sent Monthly tab view
![234670712](https://cloud.githubusercontent.com/assets/3488986/26540945/6e339dd2-445c-11e7-810e-269cea38a488.png)

**Comment by rowo** [comment]
![icon-hia2](https://user-images.githubusercontent.com/1584163/26878323-1b564d48-4b5b-11e7-8aca-a513fb28e757.png)

**Comment by cagulas** [comment]
Lgtm
